"""create session stock

Revision ID: 498bfaf0efb3
Revises: 9f1fb1ca63ef
Create Date: 2026-10-09 20:10:59.329819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '498bfaf0efb3'
down_revision: Union[str, Sequence[str], None] = '9f1fb1ca63ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_stock',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('stocked_qty', sa.Integer(), nullable=False),
    sa.Column('sold_qty', sa.Integer(), server_default='0', nullable=False),
    sa.Column('wasted_qty', sa.Integer(), server_default='0', nullable=False),
    sa.Column('min_stock', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('min_stock >= 0', name='ck_session_stock_min_nonneg'),
    sa.CheckConstraint('sold_qty + wasted_qty <= stocked_qty', name='ck_session_stock_never_negative'),
    sa.CheckConstraint('sold_qty >= 0', name='ck_session_stock_sold_nonneg'),
    sa.CheckConstraint('stocked_qty >= 0', name='ck_session_stock_stocked_nonneg'),
    sa.CheckConstraint('wasted_qty >= 0', name='ck_session_stock_wasted_nonneg'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['stall_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'product_id', name='uq_session_stock_session_product')
    )
    op.create_index(op.f('ix_session_stock_product_id'), 'session_stock', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_stock_product_id'), table_name='session_stock')
    op.drop_table('session_stock')
    # ### end Alembic commands ###
