"""add category and updated_at to products

Revision ID: 9963e737e6c3
Revises: 355961170cc3
Create Date: 2026-10-09 14:17:08.575485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9963e737e6c3'
down_revision: Union[str, Sequence[str], None] = '355961170cc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('category', sa.String(length=50), server_default='nankhatai', nullable=False))
    op.add_column('products', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_check_constraint("ck_products_price_positive", "products", "price > 0")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_products_price_positive", "products", type_="check")
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_column('products', 'updated_at')
    op.drop_column('products', 'category')
    # ### end Alembic commands ###
