"""create stall locations and sessions

Revision ID: 9f1fb1ca63ef
Revises: 9963e737e6c3
Create Date: 2026-10-09 14:39:57.005895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f1fb1ca63ef'
down_revision: Union[str, Sequence[str], None] = '9963e737e6c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stall_locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('google_place_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('latitude BETWEEN -90 AND 90', name='ck_stall_locations_latitude'),
    sa.CheckConstraint('longitude BETWEEN -180 AND 180', name='ck_stall_locations_longitude'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stall_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('scheduled', 'open', 'closed', 'cancelled')", name='ck_stall_sessions_status'),
    sa.CheckConstraint('end_time > start_time', name='ck_stall_sessions_time_order'),
    sa.ForeignKeyConstraint(['location_id'], ['stall_locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id', 'session_date', 'start_time', name='uq_stall_sessions_slot')
    )
    op.create_index('ix_stall_sessions_date_status', 'stall_sessions', ['session_date', 'status'], unique=False)
    op.create_index(op.f('ix_stall_sessions_location_id'), 'stall_sessions', ['location_id'], unique=False)
    op.create_index('uq_stall_sessions_one_open', 'stall_sessions', ['status'], unique=True, postgresql_where=sa.text("status = 'open'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_stall_sessions_one_open', table_name='stall_sessions', postgresql_where=sa.text("status = 'open'"))
    op.drop_index(op.f('ix_stall_sessions_location_id'), table_name='stall_sessions')
    op.drop_index('ix_stall_sessions_date_status', table_name='stall_sessions')
    op.drop_table('stall_sessions')
    op.drop_table('stall_locations')
    # ### end Alembic commands ###
